{
 "title": "Couchbase Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(cb_node_service_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sites RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"sites\"})"
    }
   ]
  },
  {
   "title": "Functional Settings RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"functional-settings\"})"
    }
   ]
  },
  {
   "title": "Products RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"products\"})"
    }
   ]
  },
  {
   "title": "Selling Prices RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"selling-prices\"})"
    }
   ]
  },
  {
   "title": "Nomenclatures RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"nomenclatures\"})"
    }
   ]
  },
  {
   "title": "Companies RAM Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_ram_quota_percent_used{bucket=\"companies\"})"
    }
   ]
  },
  {
   "title": "Sites Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"sites\"})"
    }
   ]
  },
  {
   "title": "Functional Settings Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"functional-settings\"})"
    }
   ]
  },
  {
   "title": "Products Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"products\"})"
    }
   ]
  },
  {
   "title": "Selling Prices Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"selling-prices\"})"
    }
   ]
  },
  {
   "title": "Nomenclatures Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"nomenclatures\"})"
    }
   ]
  },
  {
   "title": "Companies Item Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_bucket_item_count{bucket=\"companies\"})"
    }
   ]
  },
  {
   "title": "Sites Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"sites\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Functional Settings Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"functional-settings\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Products Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"products\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Selling Prices Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"selling-prices\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Nomenclatures Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"nomenclatures\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Companies Replication Completeness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cb_xdcr_percent_completeness{source_bucket=\"companies\",remote_cluster_id=\"9b557b754ba539c981f490a0a36f1f4d\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "cb_node_service_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Ops per second by bucket",
   "type": "graph",
   "description": "Operations per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cb_bucket_ops_per_second) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Current Items by bucket",
   "type": "graph",
   "description": "Current number of items in memory",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(avg(cb_bucketstats_curr_items) by (bucket))",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Disk write queue by bucket",
   "type": "graph",
   "description": "Write queue to disk",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_disk_write_queue) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Memory headroom by bucket",
   "type": "graph",
   "description": "A low value means that the bucket needs more memory",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_ep_mem_high_wat) by (bucket) - avg(cb_bucketstats_mem_used) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Resident item ratio by bucket",
   "type": "graph",
   "description": "Number of items on memory over number of items on disk",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_vb_active_resident_items_ratio) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "XDCR items sent by bucket",
   "type": "graph",
   "description": "Number of items sent through XDCR",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_ep_dcp_xdcr_items_sent) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Cache miss ratio by bucket",
   "type": "graph",
   "description": "Ratio of disk fetch instead of memory. If not zero, should be investigated",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_ep_bg_fetched) by (bucket) / (avg(cb_bucketstats_cmd_get) by (bucket) * 100)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Ejections by bucket",
   "type": "graph",
   "description": "Number of object ejections from memory. Should be zero",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_ep_num_value_ejects) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "OOM errors by bucket",
   "type": "graph",
   "description": "Number of unrecoverable out of memory errors due to memory exhaustion",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cb_bucketstats_ep_oom_errors) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  }
 ]
}